#modPath: "C:/Users/user/Documents/repos/mod/oldworldblues"
#hoi4Path: "C:/Program Files (x86)/Steam/steamapps/common/Hearts of Iron IV"
modPath: "E:/Paradox/mod/oldworldblues"
hoi4Path: "E:/SteamLibraryE/steamapps/common/Hearts of Iron IV"
colors:
  - color:
    r: 106
    g: 228
    b: 3
    a: 180
  - color:
    r: 255
    g: 245
    b: 34
    a: 180
  - color:
    r: 255
    g: 34
    b: 34
    a: 180
  - color:
    r: 34
    g: 69
    b: 255
    a: 180
  - color:
    r: 255
    g: 34
    b: 238
    a: 180