modPath: "C:/Users/user/Documents/repos/mod/oldworldblues"
hoi4Path: "C:/Program Files (x86)/Steam/steamapps/common/Hearts of Iron IV"

colors:
  - color:
    r: 255
    g: 130
    b: 10
    a: 180
  - color:
    r: 255
    g: 130
    b: 10
    a: 180