modPath: "C:/Program Files (x86)/Steam/steamapps/common/Hearts of Iron IV"
image_repeats: 3

colors:
  - color:
    r: 255
    g: 130
    b: 10
    a: 180
  - color:
    r: 255
    g: 130
    b: 10
    a: 180